cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = ["//src/lib:lib"],
    visibility = ["//visibility:public"],
)
cc_binary(
    name = "mainStatic",
    srcs = ["mainStaticCast.cpp"],
    deps = ["//src/lib:lib"],
    visibility = ["//visibility:public"],
)
cc_binary(
    name = "mainDynamic",
    srcs = ["mainDynamicCast.cpp"],
    deps = ["//src/lib:lib"],
    visibility = ["//visibility:public"],
)
