#!/bin/bash


#while getopts ":i:n:m:e:" arg; do
#  case $arg in
#    i) ID=$OPTARG;;
#    n) Name=$OPTARG;;
#    m) Manufacturing_date=$OPTARG;;
#    e) Expire_date=$OPTARG;;
#  esac
#done


echo "Building project..."
make clean;
make router;
make unit-test;
clear;

echo "Running unit test on router..."
./unit-test

echo "Testing using 4_routers.conf..."
./ne 2091 4_routers.conf&;
./router 0 localhost 2091 3091&;
./router 1 localhost 2091 4091&;
./router 2 localhost 2091 5091&;
./router 3 localhost 2091 6091&;


echo "Tests complete!";
exit(0)
